In [1]:
import pandas as pd
import numpy as np
import joblib
import gc
import scipy.stats

import matplotlib.pyplot as plt
%matplotlib inline

## Load Dataset

In [2]:
# Load the raw data
df = pd.read_csv("data/ratings.csv", encoding="ISO-8859-1")
# df = df[:20]

# Input- & Output-Variables
y1mos = df["MOS_Complexity"].values
y1std = df["Std_Complexity"].values
y2mos = df["MOS_Understandability"].values
y2std = df["Std_Understandability"].values
y3mos = df["MOS_Lexical_difficulty"].values
y3std = df["Std_Lexical_difficulty"].values
# free memory
del df
gc.collect()

0

## Lead Precomputed Features

In [3]:
with open('./data/preprocessed.npy', 'rb') as fp:
    feats1 = np.load(fp)
    feats2 = np.load(fp)
    feats3 = np.load(fp)
    feats4 = np.load(fp)
    feats5 = np.load(fp)
    feats6 = np.load(fp)
    feats7 = np.load(fp)
    feats8 = np.load(fp)
    feats9 = np.load(fp)

In [4]:
xrnd1 = np.random.random(size=feats1.shape)
xrnd1 = (xrnd1.T / xrnd1.sum(axis=1)).T

xrnd2 = np.random.random(size=feats2.shape)
xrnd2 = (xrnd2.T / xrnd2.sum(axis=1)).T

xrnd3 = np.random.random(size=feats3.shape)
xrnd3 = (xrnd3.T / xrnd3.sum(axis=1)).T

xrnd4 = np.random.random(size=feats4.shape)
xrnd4 = (xrnd4.T / xrnd4.sum(axis=1)).T

xrnd5 = np.random.random(size=feats5.shape)
xrnd5 = (xrnd5.T / xrnd5.sum(axis=1)).T

xrnd6 = np.random.random(size=feats6.shape)
xrnd6 = (xrnd6.T / xrnd6.sum(axis=1)).T

xrnd7 = np.random.random(size=feats7.shape)
xrnd7 = (xrnd7.T / xrnd7.sum(axis=1)).T

xrnd9 = np.random.random(size=feats9.shape)
xrnd9 = (xrnd9.T / xrnd9.sum(axis=1)).T

In [5]:
xinputs0 = np.hstack([feats1, feats2, feats3, feats4, feats5, feats6, feats7, feats9])
xinputs1 = np.hstack([xrnd1, feats2, feats3, feats4, feats5, feats6, feats7, feats9])
xinputs2 = np.hstack([feats1, xrnd2, feats3, feats4, feats5, feats6, feats7, feats9])
xinputs3 = np.hstack([feats1, feats2, xrnd3, feats4, feats5, feats6, feats7, feats9])
xinputs4 = np.hstack([feats1, feats2, feats3, xrnd4, feats5, feats6, feats7, feats9])
xinputs5 = np.hstack([feats1, feats2, feats3, feats4, xrnd5, feats6, feats7, feats9])
xinputs6 = np.hstack([feats1, feats2, feats3, feats4, feats5, xrnd6, feats7, feats9])
xinputs7 = np.hstack([feats1, feats2, feats3, feats4, feats5, feats6, xrnd7, feats9])
xinputs9 = np.hstack([feats1, feats2, feats3, feats4, feats5, feats6, feats7, xrnd9])

## Load Model

In [6]:
model2 = joblib.load('./models/model7-rf/model2.joblib')
model1a = joblib.load('./models/model7-rf/model1a.joblib')
model1b = joblib.load('./models/model7-rf/model1b.joblib')
model1c = joblib.load('./models/model7-rf/model1c.joblib')

## Inference

In [7]:
eps0 = model2.predict(xinputs0)
eps1 = model2.predict(xinputs1)
eps2 = model2.predict(xinputs2)
eps3 = model2.predict(xinputs3)
eps4 = model2.predict(xinputs4)
eps5 = model2.predict(xinputs5)
eps6 = model2.predict(xinputs6)
eps7 = model2.predict(xinputs7)
eps9 = model2.predict(xinputs9)

In [8]:
y0 = np.c_[
    eps0[:, 0] + model1a.predict(feats8[:, 1].reshape(-1, 1)),
    eps0[:, 1] + model1b.predict(feats8[:, 1].reshape(-1, 1)),
    eps0[:, 2] + model1c.predict(feats8[:, 1].reshape(-1, 1))
]

y1 = np.c_[
    eps1[:, 0] + model1a.predict(feats8[:, 1].reshape(-1, 1)),
    eps1[:, 1] + model1b.predict(feats8[:, 1].reshape(-1, 1)),
    eps1[:, 2] + model1c.predict(feats8[:, 1].reshape(-1, 1))
]

y2 = np.c_[
    eps2[:, 0] + model1a.predict(feats8[:, 1].reshape(-1, 1)),
    eps2[:, 1] + model1b.predict(feats8[:, 1].reshape(-1, 1)),
    eps2[:, 2] + model1c.predict(feats8[:, 1].reshape(-1, 1))
]

y3 = np.c_[
    eps3[:, 0] + model1a.predict(feats8[:, 1].reshape(-1, 1)),
    eps3[:, 1] + model1b.predict(feats8[:, 1].reshape(-1, 1)),
    eps3[:, 2] + model1c.predict(feats8[:, 1].reshape(-1, 1))
]

y4 = np.c_[
    eps4[:, 0] + model1a.predict(feats8[:, 1].reshape(-1, 1)),
    eps4[:, 1] + model1b.predict(feats8[:, 1].reshape(-1, 1)),
    eps4[:, 2] + model1c.predict(feats8[:, 1].reshape(-1, 1))
]

y5 = np.c_[
    eps5[:, 0] + model1a.predict(feats8[:, 1].reshape(-1, 1)),
    eps5[:, 1] + model1b.predict(feats8[:, 1].reshape(-1, 1)),
    eps5[:, 2] + model1c.predict(feats8[:, 1].reshape(-1, 1))
]

y6 = np.c_[
    eps6[:, 0] + model1a.predict(feats8[:, 1].reshape(-1, 1)),
    eps6[:, 1] + model1b.predict(feats8[:, 1].reshape(-1, 1)),
    eps6[:, 2] + model1c.predict(feats8[:, 1].reshape(-1, 1))
]

y7 = np.c_[
    eps7[:, 0] + model1a.predict(feats8[:, 1].reshape(-1, 1)),
    eps7[:, 1] + model1b.predict(feats8[:, 1].reshape(-1, 1)),
    eps7[:, 2] + model1c.predict(feats8[:, 1].reshape(-1, 1))
]

y9 = np.c_[
    eps9[:, 0] + model1a.predict(feats8[:, 1].reshape(-1, 1)),
    eps9[:, 1] + model1b.predict(feats8[:, 1].reshape(-1, 1)),
    eps9[:, 2] + model1c.predict(feats8[:, 1].reshape(-1, 1))
]


## Sensitivity analysis on loss function

In [9]:
l0 = np.power(np.c_[y1mos, y2mos, y3mos] - y0, 2).mean(axis=0)
l1 = np.power(np.c_[y1mos, y2mos, y3mos] - y1, 2).mean(axis=0)
l2 = np.power(np.c_[y1mos, y2mos, y3mos] - y2, 2).mean(axis=0)
l3 = np.power(np.c_[y1mos, y2mos, y3mos] - y3, 2).mean(axis=0)
l4 = np.power(np.c_[y1mos, y2mos, y3mos] - y4, 2).mean(axis=0)
l5 = np.power(np.c_[y1mos, y2mos, y3mos] - y5, 2).mean(axis=0)
l6 = np.power(np.c_[y1mos, y2mos, y3mos] - y6, 2).mean(axis=0)
l7 = np.power(np.c_[y1mos, y2mos, y3mos] - y7, 2).mean(axis=0)
l9 = np.power(np.c_[y1mos, y2mos, y3mos] - y9, 2).mean(axis=0)

print(" Complexity | Understandability | Lexical")
print("  semantic: " + '  '.join([f"{x:6.4f}" for x in l1 - l0]))
print("    syntax: " + '  '.join([f"{x:6.4f}" for x in l2 - l0]))
print("  pos tags: " + '  '.join([f"{x:6.4f}" for x in l3 - l0]))
print("morph tags: " + '  '.join([f"{x:6.4f}" for x in l4 - l0]))
print(" phonetics: " + '  '.join([f"{x:6.4f}" for x in l5 - l0]))
print(" morphemes: " + '  '.join([f"{x:6.4f}" for x in l6 - l0]))
print("lemma freq: " + '  '.join([f"{x:6.4f}" for x in l7 - l0]))
print("bigram frq: " + '  '.join([f"{x:6.4f}" for x in l9 - l0]))

 Complexity | Understandability | Lexical
  semantic: 0.2405  0.3381  0.3928
    syntax: 0.0057  0.0079  0.0108
  pos tags: 0.0086  0.0121  0.0139
morph tags: 0.0060  0.0066  0.0084
 phonetics: 0.0011  0.0011  0.0017
 morphemes: 0.0066  0.0091  0.0106
lemma freq: 0.0102  0.0158  0.0201
bigram frq: 0.0111  0.0136  0.0156


In [10]:
l0 = np.abs(np.c_[y1mos, y2mos, y3mos] - y0).mean(axis=0)
l1 = np.abs(np.c_[y1mos, y2mos, y3mos] - y1).mean(axis=0)
l2 = np.abs(np.c_[y1mos, y2mos, y3mos] - y2).mean(axis=0)
l3 = np.abs(np.c_[y1mos, y2mos, y3mos] - y3).mean(axis=0)
l4 = np.abs(np.c_[y1mos, y2mos, y3mos] - y4).mean(axis=0)
l5 = np.abs(np.c_[y1mos, y2mos, y3mos] - y5).mean(axis=0)
l6 = np.abs(np.c_[y1mos, y2mos, y3mos] - y6).mean(axis=0)
l7 = np.abs(np.c_[y1mos, y2mos, y3mos] - y7).mean(axis=0)
l9 = np.abs(np.c_[y1mos, y2mos, y3mos] - y9).mean(axis=0)

print(" Complexity | Understandability | Lexical")
print("  semantic: " + '  '.join([f"{x:6.4f}" for x in l1 - l0]))
print("    syntax: " + '  '.join([f"{x:6.4f}" for x in l2 - l0]))
print("  pos tags: " + '  '.join([f"{x:6.4f}" for x in l3 - l0]))
print("morph tags: " + '  '.join([f"{x:6.4f}" for x in l4 - l0]))
print(" phonetics: " + '  '.join([f"{x:6.4f}" for x in l5 - l0]))
print(" morphemes: " + '  '.join([f"{x:6.4f}" for x in l6 - l0]))
print("lemma freq: " + '  '.join([f"{x:6.4f}" for x in l7 - l0]))
print("bigram frq: " + '  '.join([f"{x:6.4f}" for x in l9 - l0]))

 Complexity | Understandability | Lexical
  semantic: 0.1600  0.2063  0.2247
    syntax: 0.0038  0.0050  0.0064
  pos tags: 0.0054  0.0080  0.0089
morph tags: 0.0043  0.0043  0.0055
 phonetics: 0.0008  0.0011  0.0015
 morphemes: 0.0048  0.0063  0.0068
lemma freq: 0.0081  0.0138  0.0159
bigram frq: 0.0071  0.0096  0.0101


## Feature Importance

In [11]:
xnames = [f"sbert_{j}" for j in range(feats1.shape[1])] \
    + [f"nodedist_{j}" for j in range(feats2.shape[1])] \
    + [f"postag_{j}" for j in range(feats3.shape[1])] \
    + [f"morphtag_{j}" for j in range(feats4.shape[1])] \
    + [f"consonant_{j}" for j in range(feats5.shape[1])] \
    + [f"lexemes_{j}" for j in range(feats6.shape[1])] \
    + [f"frequency_{j}" for j in range(feats7.shape[1])] \
    + [f"bigram_{j}" for j in range(feats9.shape[1])] 

df_fi = pd.DataFrame(index=xnames, data=model2.feature_importances_, columns=["fi"])
df_fi = df_fi.sort_values(by="fi", ascending=False)
df_fi.head(20)

fi
sbert_156    0.109948
sbert_173    0.038845
sbert_287    0.021552
sbert_229    0.020868
sbert_68     0.019843
frequency_2  0.016413
sbert_329    0.016284
sbert_69     0.015834
sbert_228    0.013689
sbert_369    0.013205
sbert_363    0.011027
sbert_93     0.010621
sbert_338    0.009777
bigram_3     0.009078
sbert_222    0.007992
sbert_193    0.007832
postag_11    0.006831
bigram_1     0.006803
sbert_122    0.006540
sbert_131    0.006320

In [12]:
for typ in ["sbert", "nodedist", "postag", "morphtag", "consonant", "lexemes", "frequency", "bigram"]:
    mask = [typ in r for r in df_fi.index]
    fi = df_fi.loc[mask].values
    print(f"{typ:>16s}: {fi.mean():6.4f} | {fi.max():6.4f}")

           sbert: 0.0023 | 0.1099
        nodedist: 0.0010 | 0.0020
          postag: 0.0012 | 0.0068
        morphtag: 0.0004 | 0.0021
       consonant: 0.0015 | 0.0017
         lexemes: 0.0012 | 0.0037
       frequency: 0.0041 | 0.0164
          bigram: 0.0057 | 0.0091


## Correlations

In [13]:
np.corrcoef(np.c_[y1mos, y2mos, y3mos], rowvar=False)

array([[1.        , 0.89598348, 0.90518689],
       [0.89598348, 1.        , 0.93461015],
       [0.90518689, 0.93461015, 1.        ]])

In [14]:
np.corrcoef(y0, rowvar=False)

array([[1.        , 0.98843208, 0.99312749],
       [0.98843208, 1.        , 0.99889282],
       [0.99312749, 0.99889282, 1.        ]])

In [15]:
# semantic
(np.corrcoef(y1, rowvar=False) - np.corrcoef(y0, rowvar=False)).round(4)

array([[-0.    ,  0.011 ,  0.0065],
       [ 0.011 ,  0.    ,  0.001 ],
       [ 0.0065,  0.001 ,  0.    ]])

In [16]:
# syntactic (node vs token distance)
(np.corrcoef(y2, rowvar=False) - np.corrcoef(y0, rowvar=False)).round(4)

array([[0.    , 0.0006, 0.0005],
       [0.0006, 0.    , 0.    ],
       [0.0005, 0.    , 0.    ]])

In [17]:
# pos tags
(np.corrcoef(y3, rowvar=False) - np.corrcoef(y0, rowvar=False)).round(4)

array([[ 0.    ,  0.0004,  0.0004],
       [ 0.0004,  0.    ,  0.    ],
       [ 0.0004,  0.    , -0.    ]])

In [18]:
# morph tags
(np.corrcoef(y4, rowvar=False) - np.corrcoef(y0, rowvar=False)).round(4)

array([[-0.    ,  0.0003,  0.0002],
       [ 0.0003,  0.    ,  0.    ],
       [ 0.0002,  0.    ,  0.    ]])

In [19]:
# phonetics (consonant clusters)
(np.corrcoef(y5, rowvar=False) - np.corrcoef(y0, rowvar=False)).round(4)

array([[ 0.,  0.,  0.],
       [ 0.,  0., -0.],
       [ 0., -0., -0.]])

In [20]:
# morphemes/lexemes
(np.corrcoef(y6, rowvar=False) - np.corrcoef(y0, rowvar=False)).round(4)

array([[0.    , 0.0004, 0.0002],
       [0.0004, 0.    , 0.    ],
       [0.0002, 0.    , 0.    ]])

In [21]:
# lemma freq
(np.corrcoef(y7, rowvar=False) - np.corrcoef(y0, rowvar=False)).round(4)

array([[0.    , 0.0002, 0.0002],
       [0.0002, 0.    , 0.    ],
       [0.0002, 0.    , 0.    ]])

In [22]:
# bi-gram frequency
(np.corrcoef(y9, rowvar=False) - np.corrcoef(y0, rowvar=False)).round(4)

array([[-0.    ,  0.0004,  0.0002],
       [ 0.0004,  0.    ,  0.    ],
       [ 0.0002,  0.    , -0.    ]])